### ISSUE TITLE
Adding tox after GLSL tops have been added doesn't create a connection

### ISSUE THREAD

**Issue by bravokiloecho** [vectorsize/lygia-td#2]
If I copy and paste some GLSL tops that use lygia into a new project, and then add the lygia `.tox`, a connection between the lygia `.tox` and the GLSL tops doesn't get formed. So the GLSL tops error because the lygia imports can't be read.

Is there a way to fix this?

![image](https://github.com/vectorsize/lygia-td/assets/5556900/1bdb0242-b44a-4b6b-8cf1-0c06dcd65e3b)

**Comment by vectorsize** [comment]
hi, sorry for the late reply, you can save your project and open it again, then the connection should be made automatically.
